# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdcrud', '0002_auto_20170905_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoughts',
            new_name='Tasks',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='thought',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='thoughttype',
            new_name='tasktype',
        ),
    ]
