# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdcrud', '0004_auto_20171015_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
